import type { Cue, Format, SubtitleFile } from './types.ts';
import { assToCommon } from './ass.ts';

// kind is 'header' or what a cue lost ('settings', 'style', 'karaoke'...); cues are 1-based and empty for the header.
export type Loss = { kind: string; cues: number[] };

// Cue text as SRT/WebVTT write it (<i>, <b>, <u>, \n line breaks), plus what the source format had that this drops.
function toCommon(format: Format, c: Cue, n: number): { text: string; lost: string[] } {
  if (format === 'ass' || format === 'ssa') return assToCommon(c);
  // The SAMI class only names the language, and SAMI text is already stored as SRT holds it.
  if (format === 'sami') return { text: c.text, lost: [] };
  // An id equal to the cue number comes back as SRT's own numbering, so nothing is lost.
  return { text: c.text, lost: Object.entries(c.extras ?? {}).filter(([k, v]) => !(k === 'id' && v === String(n))).map(([k]) => k) };
}

// Converting only goes to SRT, WebVTT or plain text; any format can be written back as itself.
export function convert(file: SubtitleFile, to: Format): { file: SubtitleFile; losses: Loss[] } {
  if (to === file.format) return { file, losses: [] };
  if (!['srt', 'vtt', 'txt'].includes(to)) throw new Error(`Can't convert ${file.format} to ${to}.`);

  const losses: Loss[] = [];
  // A bare "WEBVTT" line is regenerated by the writer, so only a real header counts as lost.
  if (file.header && file.header !== 'WEBVTT') losses.push({ kind: 'header', cues: [] });
  const byKind = new Map<string, number[]>();
  const cues = file.cues.map((c, i) => {
    const { text, lost } = toCommon(file.format, c, i + 1);
    for (const k of lost) byKind.set(k, [...(byKind.get(k) ?? []), i + 1]);
    return { start: c.start, end: c.end, text };
  });
  losses.push(...[...byKind].sort(([a], [b]) => a.localeCompare(b)).map(([kind, cues]) => ({ kind, cues })));
  return { file: { format: to, cues }, losses };
}
