import type { Cue, Format, SubtitleFile } from './types.ts';
import { assToCommon, commonToAss, defaultAssExtras, defaultAssHeader } from './ass.ts';
import { microDvdToCommon } from './microdvd.ts';
import { mpl2ToCommon } from './mpl2.ts';
import { commonToLrc, lrcToCommon } from './lrc.ts';

// kind is 'header' or what a cue lost ('settings', 'style', 'karaoke'...); cues are 1-based and empty for the header.
export type Loss = { kind: string; cues: number[] };

// Cue text as SRT/WebVTT write it (<i>, <b>, <u>, \n line breaks), plus what the source format had that this drops.
function toCommon(format: Format, c: Cue, n: number): { text: string; lost: string[] } {
  if (format === 'ass' || format === 'ssa') return assToCommon(c);
  // The SAMI class only names the language, and SAMI text is already stored as SRT holds it.
  if (format === 'sami') return { text: c.text, lost: [] };
  if (format === 'microdvd') return microDvdToCommon(c);
  if (format === 'mpl2') return mpl2ToCommon(c);
  if (format === 'lrc') return lrcToCommon(c);
  // An id equal to the cue number comes back as SRT's own numbering, so nothing is lost.
  return { text: c.text, lost: Object.entries(c.extras ?? {}).filter(([k, v]) => !(k === 'id' && v === String(n))).map(([k]) => k) };
}

// Converting goes to SRT, WebVTT, plain text, LRC or ASS; any format can be written back as itself.
// ASS output gets a default header with one Default style (the "Save as ASS" button on the style tools).
export function convert(file: SubtitleFile, to: Format): { file: SubtitleFile; losses: Loss[] } {
  if (to === file.format) return { file, losses: [] };
  if (!['srt', 'vtt', 'txt', 'lrc', 'ass'].includes(to)) throw new Error(`Can't convert ${file.format} to ${to}.`);

  const losses: Loss[] = [];
  // A bare "WEBVTT" line is regenerated by the writer, so only a real header counts as lost.
  // The MicroDVD header is only the frame rate, which the times already account for.
  if (file.header && file.header !== 'WEBVTT' && file.format !== 'microdvd') losses.push({ kind: 'header', cues: [] });
  const byKind = new Map<string, number[]>();
  const cues = file.cues.map((c, i) => {
    const common = toCommon(file.format, c, i + 1);
    const { text, lost } = to === 'ass' ? commonToAss(common.text) : to === 'lrc' ? commonToLrc(common.text) : { text: common.text, lost: [] };
    for (const k of new Set([...common.lost, ...lost])) byKind.set(k, [...(byKind.get(k) ?? []), i + 1]);
    return to === 'ass' ? { start: c.start, end: c.end, text, extras: { ...defaultAssExtras } } : { start: c.start, end: c.end, text };
  });
  // LRC has no end times: a line ends where the next one starts, so one that overlaps the next is cut short.
  if (to === 'lrc') {
    const cut = file.cues.flatMap((c, i) => (i + 1 < file.cues.length && c.end > file.cues[i + 1].start ? [i + 1] : []));
    if (cut.length) byKind.set('overlap', cut);
  }
  losses.push(...[...byKind].sort(([a], [b]) => a.localeCompare(b)).map(([kind, cues]) => ({ kind, cues })));
  return { file: { format: to, header: to === 'ass' ? defaultAssHeader : undefined, cues }, losses };
}
