import type { Format, SubtitleFile } from './types.ts';

// kind is 'header' or an extras key ('id', 'settings'); cues are 1-based and empty for the header.
export type Loss = { kind: string; cues: number[] };

export function convert(file: SubtitleFile, to: Format): { file: SubtitleFile; losses: Loss[] } {
  if (to === file.format) return { file, losses: [] };

  const losses: Loss[] = [];
  // A bare "WEBVTT" line is regenerated by the writer, so only a real header counts as lost.
  if (file.header && file.header !== 'WEBVTT') losses.push({ kind: 'header', cues: [] });
  const byKind = new Map<string, number[]>();
  file.cues.forEach((c, i) => {
    for (const [k, v] of Object.entries(c.extras ?? {})) {
      // An id equal to the cue number comes back as SRT's own numbering, so nothing is lost.
      if (k === 'id' && v === String(i + 1)) continue;
      byKind.set(k, [...(byKind.get(k) ?? []), i + 1]);
    }
  });
  losses.push(...[...byKind].sort(([a], [b]) => a.localeCompare(b)).map(([kind, cues]) => ({ kind, cues })));

  const cues = file.cues.map(({ extras, ...c }) => c);
  return { file: { format: to, cues }, losses };
}
